version: '3'
services:
  ubuntu:
    container_name: ubuntu_container
    build: ./ubuntu
    links:
      - mysql
    command: tail -F anything
      
  mysql:
    container_name: mysql_container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userinfo
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      
  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
  
  node:
    container_name: node_container
    build: ./node
    expose:
      - 3000
    links:
      - mysql
    command: npm start

  apache:
    container_name: apache_container
    build: ./apache
    links:
      - node
      - mysql
    ports:
      - 8080:80

volumes:
  dbdata:
